name: Build
on:
  push:
    branches: [ master ] # 当代码推送到 main 分支时触发
  workflow_dispatch: # 保留手动触发的选项

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - uses: actions/setup-java@v5
      with:
        distribution: temurin
        java-version: 17
        cache: gradle
    - name: Set up Android SDK
      uses: android-actions/setup-android@v3.2.2
      with:
        api-level: '34'
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v5
      with:
        gradle-version: '8.7'
    - run: |
        gradle :module:assembleRelease
    - uses: actions/upload-artifact@v4 
      with:
        name: zygisk-imgui-modmenu
        path: out/magisk_module_release/