name: Build
on:
  push:
    branches: [ prop ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v5
    
    # Java 和 Gradle 设置
    - uses: actions/setup-java@v5
      with:
        distribution: temurin
        java-version: 17
        cache: gradle
    
    
    # 方法3：使用 GitHub 官方的 Android 设置（推荐）
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3.2.2
      with:
        # 最小化配置，只安装必须的
        cmdline-tools-version: 11479570 
    
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v5
      with:
        gradle-version: '8.7'
    
    - name: Build with Gradle
      run: |
        gradle :module:assembleRelease
    
    - uses: actions/upload-artifact@v4
      with:
        name: zygisk-imgui-modmenu
        path: module/build/magisk_module_release/